import { createServerFn } from "@tanstack/react-start";

/**
 * Temporary email-only staging login.
 *
 * This deliberately bypasses mailbox verification and must be removed when
 * normal authentication is enabled. The service key remains server-side; the
 * browser receives only a single-use hashed token generated by Supabase.
 */
export const createEmailOnlyLogin = createServerFn({ method: "POST" })
  .inputValidator((data: { email: string }) => data)
  .handler(async ({ data }) => {
    const email = data.email.trim().toLowerCase();
    if (!email) throw new Error("Email is required");

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: profile, error: profileError } = await supabaseAdmin
      .from("profiles")
      .select("id, is_active")
      .eq("email", email)
      .maybeSingle();

    if (profileError) throw new Error(profileError.message);
    if (!profile || profile.is_active === false) {
      throw new Error("This email is not registered as an active user.");
    }

    const { data: link, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "magiclink",
      email,
    });
    if (error) throw new Error(error.message);

    const tokenHash = link.properties?.hashed_token;
    if (!tokenHash) throw new Error("Could not create a temporary login token.");

    return { tokenHash };
  });
