(()=>{
  document.querySelector('.app-version-badge')?.replaceChildren('Version 79');
  const url='https://ewjalucwaeotamodlajs.supabase.co';
  const key='sb_publishable_XeGECEGDBFj1b0z-zyb2kQ_SdlTL2tG';
  const button=document.getElementById('recordButton');
  const status=document.getElementById('recorderStatus');
  const form=document.getElementById('recordDraft');
  let recorder,stream,chunks=[],started=0,timer,draft,creating=false;
  const session=()=>window.shgGetSupabaseSession?.();
  const request=async(path,options={})=>{const active=await window.shgEnsureFreshSession?.(60000);if(!active?.access_token)throw new Error('Please sign in first.');const response=await fetch(`${url}/functions/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${active.access_token}`,...options.headers}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'The request failed.');return data};
  const fillSelect=(element,items,selected)=>{element.innerHTML=items.map(item=>`<option value="${String(item.value).replaceAll('"','&quot;')}" ${item.value===selected?'selected':''}>${item.label}</option>`).join('')};
  const showResult=(kind,html)=>{status.className=`recorder-result ${kind}`;status.innerHTML=html;status.scrollIntoView({behavior:'smooth',block:'center'})};
  async function start(){status.className='';stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=process;recorder.start();started=Date.now();button.classList.add('recording');button.textContent='■';status.textContent='Recording… Press again when you finish.';timer=setInterval(()=>{const seconds=Math.floor((Date.now()-started)/1000);document.getElementById('recordingTimer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},500)}
  function stop(){clearInterval(timer);recorder.stop();stream.getTracks().forEach(track=>track.stop());button.classList.remove('recording');button.textContent='●';button.disabled=true;status.textContent='Transcribing and preparing the Task…'}
  async function process(){try{const mime=recorder.mimeType||'audio/webm',extension=mime.includes('mp4')?'m4a':'webm',blob=new Blob(chunks,{type:mime}),data=new FormData();data.append('file',blob,`Mailo Recording ${new Date().toISOString().replaceAll(':','-')}.${extension}`);draft=await request('import-voice-memo',{method:'POST',body:data});const d=draft.draft,context=await request('voice-task-api/context');form.type.value=d.type;fillSelect(form.space,context.spaces.map(space=>({value:space.name,label:space.name})),d.spaceName);fillSelect(form.assignee,[{value:'',label:'Unassigned'},...context.users.map(user=>({value:user.name,label:user.name}))],d.assignee==='Unassigned'?'':d.assignee);fillSelect(form.supervisor,[{value:'',label:'Unassigned'},...context.users.map(user=>({value:user.name,label:user.name}))],d.supervisor==='Unassigned'?'':d.supervisor);form.title.value=d.title;form.priority.value=d.priority;form.dueDate.value=d.dueDate||'';form.description.value=d.description||'';document.getElementById('recordTranscript').textContent=draft.transcript;document.getElementById('recordWarnings').textContent=(draft.warnings||[]).join(' ');form.classList.remove('hidden');status.className='';status.textContent='Review the fields and create the Task when ready.'}catch(error){showResult('error',`<strong>The recording could not be prepared.</strong><br>${error.message}`);button.disabled=false}}
  button.onclick=async()=>{try{if(recorder?.state==='recording')stop();else await start()}catch(error){showResult('error',`<strong>Recording could not start.</strong><br>${error.message}`)}};
  document.getElementById('discardRecording').onclick=()=>location.reload();
  form.onsubmit=async event=>{event.preventDefault();if(creating)return;creating=true;const data=new FormData(form),submit=form.querySelector('[type="submit"]');submit.disabled=true;submit.textContent='Creating…';try{const result=await request('voice-task-api/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:data.get('type'),title:data.get('title'),description:data.get('description'),space:data.get('space'),assignee:data.get('assignee')||null,supervisor:data.get('supervisor')||null,priority:data.get('priority'),dueDate:data.get('dueDate')||null,labels:[],explicitFields:['assignee',...(data.get('supervisor')?['supervisor']:[]),...(data.get('space')?['space']:[])],confirmed:true})});form.classList.add('hidden');showResult('success',`<strong>Task ${result.taskKey} created successfully.</strong><span class="record-result-actions"><a href="${result.url}">Open Task</a><button type="button" onclick="location.reload()">Record Another Task</button></span>`);button.disabled=true}catch(error){creating=false;submit.disabled=false;submit.textContent='Try Again';showResult('error',`<strong>The Task was not created.</strong><br>${error.message}<br><small>Your recording and fields have been kept. Correct anything needed and press Try Again.</small>`)}};
  if(!session())document.querySelector('.recorder-shell').classList.add('hidden');
})();
